dist: xenial
sudo: required
language: java

env:
  global:
    - SONATYPE_USERNAME=ph@phloc.com
    - secure: "qo/Ht1CE4Pk491evUeY5CJydCVGSBUUSbDIfy2m4eg7uzxhFOdFAM9MaJ7NBuYZItWKeZw10KvwQsbOf6GfwoGnR5
H9kpoMBKt/KTRWXNPsVsj4eMOUhr26lf9Ph7vfH5B49Fi2hkj/YFgj4qLRNmwobT5uCpxmx+k35Ms7j5lKcIXkZboFsu10BviTxh
fZ85fxKB/bZIVad7V5slH1AWhTE715kWvUMqO+HqPQv3yXknh4ffFZJWH6kGp0gmK8oFBhJB/sq48trtYU+hX9GcDRSm+ecTw2+3
iZ4aKRc5Ei4MkMtnse0U3zy7QMGlaFxTcMoHfGrz5rN9sMB/U6U+BEnqobtnjFJPbnlupam2qMe4kDHTasTKYPNp7Dpwv1HpNkD8
hnP271b5r1nF+3zrm/c/FLV90rm39CPCq2CtlQ9yvoMk3cNjvtVm6nKDfW4+EgSqFRDlyGBhJgsfTpa9ENl9JnHKnZqQ9lIgpS6h
UW0XbXpo34OwRkAWnQTbU4rAotheaOqO9TweYdKri4C3m28FdDFcgxWtQPI97KmBi6rVMjEFgjs4/sohl8XtDKXo5eqDUHtChc0b
aXvGcebsQ6dpiRVLOS/lFoRvsqODeFLMJ1lfW5kIfp/pTK45cOXnq1XJpzFUGWOVIL0PygXrLM0N7ShvrDvuRZsdnqK93I="

addons:
  sonarcloud:
    organization: "phax-github"
    token:
      secure: "PLCZNxlCbReNUzh1V1Ap8l6RdWBAqetUaAVLd8U5jCk8oF0/C++fpjLS0nXwsXpMqY4kQ9/TREMYiif2IR0hObk5XOOG2hsE6MH3eBehtzYHKOApzkk7IsRGULihJWcpn12jTmXoxGHIR16SEiPJ8
c1Pnug3IhgpTck3sfXLllHA5S/4HSPNoZnFJ5YvL/EYxtr8KDlF8+scaA7PKCUa/lS3Ycv5hfgOaQN91ElF1F14AlepPeFX2M52/53NP8+xy3WVS6kE3jkVJBJDnfIBMbjCErxYnUvt8iqqzAvkrvWYI+KPw2+NL
rhnu1REfQ5gY5J73F0zcMSspK8L7o5PvQz2MtW2BLOXlIohjFx/V8cybbYcnjttcvSBe1KE+k6rPqFEAqW99yKlitV9BzycQKjmuvypg+7tUkhfYgyntS3tmRRyJJShX8N76e44Mo/HB/Mv85Xbx5Hx2/ujDT1Wm
W+/JhJKTOPagJtgQ5Au6M036V0CRGzxZQciqgWgbaR4ehlWY9ZdE8g/wfidVkxa2d/8zgVdt93gyoFt0X3njDeua4Bh0Hqem2aA7uvT7owYcstZZJen2k/G4MmVzaI9SKi6skwee1YQS1TBcWdfkIkMGRR0CsaoY
DNMU1dbYy3svuJOc7kE8Ly81a1mxiexktfE2YqqHQWe9HkZW6QHo80="
  
install:
#  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U -P jdeps
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U -e

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      jdk: openjdk8
      script:
        - mvn test -B -P coverage
      after_success:
        - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
        - bash <(curl -s https://codecov.io/bash)
    - stage: test
      jdk: openjdk11
      script:
        - mvn test -B sonar:sonar
    - stage: test
      jdk: openjdk14
      script:
        - mvn test -B
